// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/21/2026, 4:10:53 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["/Users/jb/code/VAN-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jb/code/VAN-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jb/code/VAN-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jb/code/VAN-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jb/code/VAN-frontend/plugins/**/*.{js,ts,mjs}","/Users/jb/code/VAN-frontend/composables/**/*.{js,ts,mjs}","/Users/jb/code/VAN-frontend/utils/**/*.{js,ts,mjs}","/Users/jb/code/VAN-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jb/code/VAN-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/jb/code/VAN-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/jb/code/VAN-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;